/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { PointlessCurrencyERC20Contract } from "./PointlessCurrencyERC20";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "PointlessCurrencyERC20"): PointlessCurrencyERC20Contract;
    }
  }
}

export {
  PointlessCurrencyERC20Contract,
  PointlessCurrencyERC20Instance,
} from "./PointlessCurrencyERC20";
